server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: athena-config
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.224:3306/athena-config?useSSL=false
    username: root
    password: cloudos
  zipkin:
    base-url: http://192.168.0.225:9411
  sleuth:
    sampler:
      percentage: 1.0  #默认为0.1
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.225:8761/eureka/
  instance:
      prefer-ip-address: true
ribbon:
  ReadTimeout: 60000
  SocketTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000 #延长触发熔断超时时间，解决第一次请求报Timeout的问题
feign:
  hystrix:
    enabled: true
mybatis:
  type-aliases-package: com.h3c.vdi.athena.configserver.model.entity