version: '3'
services:
  mysql-server:
    image: "mysql-server:forever"
    restart: always
    build: mysql-server/target
    ports:
      - 3308:3306
    volumes:
      - /opt/H3C/athena/mysql/data:/var/lib/mysql
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: 1q2w3e
    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
    container_name: mysql-server


