server:
  port: ${NETDISK_PORT}
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: athena-netdisk
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
  zipkin:
    base-url: http://${HYSTRIX_HOSTNAME}:${HYSTRIX_PORT}
  sleuth:
    sampler:
      percentage: 1.0  #默认为0.1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/athena-nextcloud?useSSL=false
    username: ${DATABASE_USER}
    password: ${DATABASE_PWD}
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_INSTANCE_HOSTNAME}:${EUREKA_INSTANCE_PORT}/eureka/
  instance:
      prefer-ip-address: true
#超时时间配置，方便联调。
ribbon:
  ReadTimeout: 60000
  SocketTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000 #延长触发熔断超时时间，解决第一次请求报Timeout的问题
feign:
  hystrix:
    enabled: true
mybatis:
  type-aliases-package: com.h3c.vdi.athena.netdisk.model.entity